# Generated by Django 3.1.7 on 2021-03-05 08:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('drf_jwt_otp', '0002_otpdevicetoken_valid_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpdevicetoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 3, 5, 8, 24, 56, 593617, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
