# Generated by Django 3.1.7 on 2021-03-05 13:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drf_jwt_otp', '0003_otpdevicetoken_created_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='otpdevicetoken',
            unique_together={('user', 'device_persistent_id')},
        ),
    ]
